"""add_allowed_modules_to_companies

Revision ID: bbcf13923d1a
Revises: 40d4c6d224e6
Create Date: 2026-04-15 07:24:05.311920

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "bbcf13923d1a"
down_revision: Union[str, Sequence[str], None] = "40d4c6d224e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "companies",
        sa.Column(
            "allowed_modules",
            sa.dialects.postgresql.JSONB(),
            server_default='["finance"]',
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("companies", "allowed_modules")
    # ### end Alembic commands ###
